name: Bayesian Clinical Trial CI/CD


on:

  push:

    branches: [ main, dev ]

  pull_request:

    branches: [ main ]


env:

  R_VERSION: '4.1.0'  # Matches your Dockerfile

  DOCKER_IMAGE: 'bayesian-clinical-trial'

  DOCKER_TAG: latest


jobs:

  test:

    name: Test and Validate

    runs-on: ubuntu-latest

    

    steps:

      - uses: actions/checkout@v4


      - name: Set up R

        uses: r-lib/actions/setup-r@v2

        with:

          r-version: ${{ env.R_VERSION }}

          use-public-rspm: true


      - name: Install system dependencies

        run: |

          sudo apt-get update

          sudo apt-get install -y \

            libcurl4-openssl-dev \

            libssl-dev \

            libxml2-dev \

            pandoc \

            texlive-latex-base


      - name: Install R dependencies

        run: |

          Rscript -e 'install.packages(c("renv", "testthat"))'

          Rscript -e 'renv::restore()'


      - name: Run tests

        run: |

          Rscript -e 'testthat::test_dir("tests/")'


      - name: Validate models

        run: Rscript scripts/validate_models.R


      - name: Upload test results

        uses: actions/upload-artifact@v4

        if: always()

        with:

          name: test-results

          path: |

            test_outputs/

            validation_results.csv

            validation_plot.png


  build-and-push:

    name: Build and Push Docker Image

    needs: test

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    

    steps:

      - uses: actions/checkout@v4


      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v2


      - name: Login to Docker Hub

        uses: docker/login-action@v2

        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}

          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: Build and push Docker image

        uses: docker/build-push-action@v4

        with:

          push: true

          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

          build-args: |

            R_VERSION=${{ env.R_VERSION }}


  deploy:

    name: Deploy to Production

    needs: build-and-push

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    

    steps:

      - name: Checkout code

        uses: actions/checkout@v4


      - name: Install kubectl

        uses: azure/setup-kubectl@v3

        if: env.KUBE_CONFIG != ''


      - name: Deploy to Kubernetes

        env:

          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

        run: |

          kubectl apply -f k8s/deployment.yaml

          kubectl rollout status deployment/bayesian-clinical-trial